# Generated by Django 3.1.3 on 2021-01-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_Movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
