# Generated by Django 3.1.3 on 2021-01-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i_Movie', '0002_movie_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='screen_shot',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_shot', models.ImageField(upload_to='screenshot/')),
                ('screenshot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='i_Movie.movie')),
            ],
        ),
    ]
